services:
  - type: web
    name: ghure-livestock-investments-ltd
    runtime: node
    rootDir: my-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; font-src 'self' https://fonts.gstatic.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; script-src 'self'; connect-src 'self' https://ghure-livestock-investments-ltd.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
